Sat Apr 12 2014 19:21:00 GMT+0000 (Coordinated Universal Time): Unaught exception: Error: failed to connect to [localhost:27017]
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:553:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:140:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:512:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
Sat Apr 12 2014 19:22:31 GMT+0000 (Coordinated Universal Time): Unaught exception: Error: failed to connect to [localhost:27017]
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:553:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:140:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:512:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
Sat Apr 12 2014 19:25:49 GMT+0000 (Coordinated Universal Time): Unaught exception: Error: failed to connect to [localhost:27017]
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:553:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:140:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:512:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
Sat Apr 12 2014 19:30:56 GMT+0000 (Coordinated Universal Time): Unaught exception: Error: failed to connect to [localhost:27017]
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:553:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:140:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:512:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
Sat Apr 12 2014 19:31:11 GMT+0000 (Coordinated Universal Time): Unaught exception: Error: failed to connect to [localhost:27017]
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:553:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:140:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:512:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
Sat Apr 12 2014 19:37:17 GMT+0000 (Coordinated Universal Time): Unaught exception: Error: failed to connect to [localhost:27017]
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:553:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:140:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:512:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
Sat Apr 12 2014 19:37:21 GMT+0000 (Coordinated Universal Time): Unaught exception: Error: failed to connect to [localhost:27017]
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:553:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:140:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:512:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
Sat Apr 12 2014 19:41:36 GMT+0000 (Coordinated Universal Time): Unaught exception: Error: failed to connect to [localhost:27017]
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:553:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:140:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:512:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
Sat Apr 12 2014 19:46:11 GMT+0000 (Coordinated Universal Time): Unaught exception: Error: failed to connect to [localhost:27017]
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:553:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:140:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:512:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
Sat Apr 12 2014 19:46:15 GMT+0000 (Coordinated Universal Time): Unaught exception: Error: failed to connect to [localhost:27017]
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:553:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:140:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:512:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
Sat Apr 12 2014 19:46:44 GMT+0000 (Coordinated Universal Time): Unaught exception: Error: failed to connect to [localhost:27017]
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:553:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:140:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:512:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
Sat Apr 12 2014 19:46:49 GMT+0000 (Coordinated Universal Time): Unaught exception: Error: failed to connect to [localhost:27017]
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:553:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:140:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:512:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
Sat Apr 12 2014 19:46:55 GMT+0000 (Coordinated Universal Time): Unaught exception: Error: failed to connect to [localhost:27017]
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:553:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:140:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:512:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
Sat Apr 12 2014 19:46:59 GMT+0000 (Coordinated Universal Time): Unaught exception: Error: failed to connect to [localhost:27017]
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:553:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:140:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:512:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
Sat Apr 12 2014 23:37:10 GMT+0000 (Coordinated Universal Time): Unaught exception: TypeError: Cannot call method 'model' of undefined
    at Object.module.exports (D:\home\site\wwwroot\models\usuario.js:15:12)
    at D:\home\site\wwwroot\node_modules\express-load\lib\express-load.js:216:17
    at iterate (D:\home\site\wwwroot\node_modules\express-load\node_modules\async\lib\async.js:131:13)
    at Object.async.eachSeries (D:\home\site\wwwroot\node_modules\express-load\node_modules\async\lib\async.js:147:9)
    at ExpressLoad.into (D:\home\site\wwwroot\node_modules\express-load\lib\express-load.js:202:9)
    at Object.<anonymous> (D:\home\site\wwwroot\server.js:30:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
Sat Apr 12 2014 23:37:10 GMT+0000 (Coordinated Universal Time): Unaught exception: Error: EBUSY, resource busy or locked 'D:\home\site\wwwroot\node_modules\express\node_modules\send\node_modules\mime\types\mime.types'
    at Object.fs.openSync (fs.js:427:18)
    at Object.fs.readFileSync (fs.js:284:15)
    at Mime.load (D:\home\site\wwwroot\node_modules\express\node_modules\send\node_modules\mime\mime.js:54:20)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\express\node_modules\send\node_modules\mime\mime.js:90:6)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
Sun Apr 13 2014 00:01:40 GMT+0000 (Coordinated Universal Time): Unaught exception: TypeError: Cannot call method 'model' of undefined
    at Object.module.exports (D:\home\site\wwwroot\models\usuario.js:15:12)
    at D:\home\site\wwwroot\node_modules\express-load\lib\express-load.js:216:17
    at iterate (D:\home\site\wwwroot\node_modules\express-load\node_modules\async\lib\async.js:131:13)
    at Object.async.eachSeries (D:\home\site\wwwroot\node_modules\express-load\node_modules\async\lib\async.js:147:9)
    at ExpressLoad.into (D:\home\site\wwwroot\node_modules\express-load\lib\express-load.js:202:9)
    at Object.<anonymous> (D:\home\site\wwwroot\server.js:30:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
Sun Apr 13 2014 00:01:44 GMT+0000 (Coordinated Universal Time): Unaught exception: TypeError: Cannot call method 'model' of undefined
    at Object.module.exports (D:\home\site\wwwroot\models\usuario.js:15:12)
    at D:\home\site\wwwroot\node_modules\express-load\lib\express-load.js:216:17
    at iterate (D:\home\site\wwwroot\node_modules\express-load\node_modules\async\lib\async.js:131:13)
    at Object.async.eachSeries (D:\home\site\wwwroot\node_modules\express-load\node_modules\async\lib\async.js:147:9)
    at ExpressLoad.into (D:\home\site\wwwroot\node_modules\express-load\lib\express-load.js:202:9)
    at Object.<anonymous> (D:\home\site\wwwroot\server.js:30:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
Sun Apr 13 2014 00:04:07 GMT+0000 (Coordinated Universal Time): Unaught exception: TypeError: Cannot call method 'model' of undefined
    at Object.module.exports (D:\home\site\wwwroot\models\usuario.js:15:12)
    at D:\home\site\wwwroot\node_modules\express-load\lib\express-load.js:216:17
    at iterate (D:\home\site\wwwroot\node_modules\express-load\node_modules\async\lib\async.js:131:13)
    at Object.async.eachSeries (D:\home\site\wwwroot\node_modules\express-load\node_modules\async\lib\async.js:147:9)
    at ExpressLoad.into (D:\home\site\wwwroot\node_modules\express-load\lib\express-load.js:202:9)
    at Object.<anonymous> (D:\home\site\wwwroot\server.js:30:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
Sun Apr 13 2014 00:06:07 GMT+0000 (Coordinated Universal Time): Unaught exception: TypeError: Cannot call method 'model' of undefined
    at Object.module.exports (D:\home\site\wwwroot\models\usuario.js:15:12)
    at D:\home\site\wwwroot\node_modules\express-load\lib\express-load.js:216:17
    at iterate (D:\home\site\wwwroot\node_modules\express-load\node_modules\async\lib\async.js:131:13)
    at Object.async.eachSeries (D:\home\site\wwwroot\node_modules\express-load\node_modules\async\lib\async.js:147:9)
    at ExpressLoad.into (D:\home\site\wwwroot\node_modules\express-load\lib\express-load.js:202:9)
    at Object.<anonymous> (D:\home\site\wwwroot\server.js:30:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
Sun Apr 13 2014 00:08:47 GMT+0000 (Coordinated Universal Time): Unaught exception: TypeError: Cannot call method 'model' of undefined
    at Object.module.exports (D:\home\site\wwwroot\models\usuario.js:15:12)
    at D:\home\site\wwwroot\node_modules\express-load\lib\express-load.js:216:17
    at iterate (D:\home\site\wwwroot\node_modules\express-load\node_modules\async\lib\async.js:131:13)
    at Object.async.eachSeries (D:\home\site\wwwroot\node_modules\express-load\node_modules\async\lib\async.js:147:9)
    at ExpressLoad.into (D:\home\site\wwwroot\node_modules\express-load\lib\express-load.js:202:9)
    at Object.<anonymous> (D:\home\site\wwwroot\server.js:30:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
Sun Apr 13 2014 00:08:51 GMT+0000 (Coordinated Universal Time): Unaught exception: TypeError: Cannot call method 'model' of undefined
    at Object.module.exports (D:\home\site\wwwroot\models\usuario.js:15:12)
    at D:\home\site\wwwroot\node_modules\express-load\lib\express-load.js:216:17
    at iterate (D:\home\site\wwwroot\node_modules\express-load\node_modules\async\lib\async.js:131:13)
    at Object.async.eachSeries (D:\home\site\wwwroot\node_modules\express-load\node_modules\async\lib\async.js:147:9)
    at ExpressLoad.into (D:\home\site\wwwroot\node_modules\express-load\lib\express-load.js:202:9)
    at Object.<anonymous> (D:\home\site\wwwroot\server.js:30:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
Sun Apr 13 2014 00:10:26 GMT+0000 (Coordinated Universal Time): Unaught exception: TypeError: Cannot call method 'model' of undefined
    at Object.module.exports (D:\home\site\wwwroot\models\usuario.js:15:12)
    at D:\home\site\wwwroot\node_modules\express-load\lib\express-load.js:216:17
    at iterate (D:\home\site\wwwroot\node_modules\express-load\node_modules\async\lib\async.js:131:13)
    at Object.async.eachSeries (D:\home\site\wwwroot\node_modules\express-load\node_modules\async\lib\async.js:147:9)
    at ExpressLoad.into (D:\home\site\wwwroot\node_modules\express-load\lib\express-load.js:202:9)
    at Object.<anonymous> (D:\home\site\wwwroot\server.js:30:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
Sun Apr 13 2014 00:10:30 GMT+0000 (Coordinated Universal Time): Unaught exception: TypeError: Cannot call method 'model' of undefined
    at Object.module.exports (D:\home\site\wwwroot\models\usuario.js:15:12)
    at D:\home\site\wwwroot\node_modules\express-load\lib\express-load.js:216:17
    at iterate (D:\home\site\wwwroot\node_modules\express-load\node_modules\async\lib\async.js:131:13)
    at Object.async.eachSeries (D:\home\site\wwwroot\node_modules\express-load\node_modules\async\lib\async.js:147:9)
    at ExpressLoad.into (D:\home\site\wwwroot\node_modules\express-load\lib\express-load.js:202:9)
    at Object.<anonymous> (D:\home\site\wwwroot\server.js:30:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
Sun Apr 13 2014 00:14:00 GMT+0000 (Coordinated Universal Time): Unaught exception: TypeError: Cannot call method 'model' of undefined
    at Object.module.exports (D:\home\site\wwwroot\models\usuario.js:15:12)
    at D:\home\site\wwwroot\node_modules\express-load\lib\express-load.js:216:17
    at iterate (D:\home\site\wwwroot\node_modules\express-load\node_modules\async\lib\async.js:131:13)
    at Object.async.eachSeries (D:\home\site\wwwroot\node_modules\express-load\node_modules\async\lib\async.js:147:9)
    at ExpressLoad.into (D:\home\site\wwwroot\node_modules\express-load\lib\express-load.js:202:9)
    at Object.<anonymous> (D:\home\site\wwwroot\server.js:30:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
Sun Apr 13 2014 00:14:04 GMT+0000 (Coordinated Universal Time): Unaught exception: TypeError: Cannot call method 'model' of undefined
    at Object.module.exports (D:\home\site\wwwroot\models\usuario.js:15:12)
    at D:\home\site\wwwroot\node_modules\express-load\lib\express-load.js:216:17
    at iterate (D:\home\site\wwwroot\node_modules\express-load\node_modules\async\lib\async.js:131:13)
    at Object.async.eachSeries (D:\home\site\wwwroot\node_modules\express-load\node_modules\async\lib\async.js:147:9)
    at ExpressLoad.into (D:\home\site\wwwroot\node_modules\express-load\lib\express-load.js:202:9)
    at Object.<anonymous> (D:\home\site\wwwroot\server.js:30:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
Sun Apr 13 2014 00:16:14 GMT+0000 (Coordinated Universal Time): Unaught exception: Error: failed to connect to [undefined:27017]
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:553:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:140:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:512:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:830:16
    at process._tickCallback (node.js:415:13)
Sun Apr 13 2014 00:16:19 GMT+0000 (Coordinated Universal Time): Unaught exception: Error: failed to connect to [undefined:27017]
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:553:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:140:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:512:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:830:16
    at process._tickCallback (node.js:415:13)
Sun Apr 13 2014 00:16:31 GMT+0000 (Coordinated Universal Time): Unaught exception: Error: failed to connect to [undefined:27017]
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:553:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:140:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:512:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:830:16
    at process._tickCallback (node.js:415:13)
Sun Apr 13 2014 00:16:35 GMT+0000 (Coordinated Universal Time): Unaught exception: Error: failed to connect to [undefined:27017]
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:553:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:140:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:512:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:830:16
    at process._tickCallback (node.js:415:13)
Sun Apr 13 2014 00:16:42 GMT+0000 (Coordinated Universal Time): Unaught exception: Error: failed to connect to [undefined:27017]
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:553:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:140:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:512:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:830:16
    at process._tickCallback (node.js:415:13)
Sun Apr 13 2014 00:16:47 GMT+0000 (Coordinated Universal Time): Unaught exception: Error: failed to connect to [undefined:27017]
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:553:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:140:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:512:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:830:16
    at process._tickCallback (node.js:415:13)
Sun Apr 13 2014 00:19:53 GMT+0000 (Coordinated Universal Time): Unaught exception: Error: failed to connect to [undefined:27017]
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:553:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:140:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:512:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:830:16
    at process._tickCallback (node.js:415:13)
Sun Apr 13 2014 00:19:57 GMT+0000 (Coordinated Universal Time): Unaught exception: Error: failed to connect to [undefined:27017]
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:553:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:140:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:512:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:830:16
    at process._tickCallback (node.js:415:13)
Sun Apr 13 2014 00:20:01 GMT+0000 (Coordinated Universal Time): Unaught exception: Error: failed to connect to [undefined:27017]
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:553:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:140:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:512:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:830:16
    at process._tickCallback (node.js:415:13)
Sun Apr 13 2014 00:20:11 GMT+0000 (Coordinated Universal Time): Unaught exception: Error: failed to connect to [undefined:27017]
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:553:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:140:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:512:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:830:16
    at process._tickCallback (node.js:415:13)
Sun Apr 13 2014 00:20:15 GMT+0000 (Coordinated Universal Time): Unaught exception: Error: failed to connect to [undefined:27017]
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:553:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:140:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:512:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:830:16
    at process._tickCallback (node.js:415:13)
Sun Apr 13 2014 00:21:41 GMT+0000 (Coordinated Universal Time): Unaught exception: Error: failed to connect to [undefined:27017]
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:553:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:140:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:512:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:830:16
    at process._tickCallback (node.js:415:13)
Sun Apr 13 2014 00:21:45 GMT+0000 (Coordinated Universal Time): Unaught exception: Error: failed to connect to [undefined:27017]
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:553:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:140:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:512:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:830:16
    at process._tickCallback (node.js:415:13)
Sun Apr 13 2014 00:22:15 GMT+0000 (Coordinated Universal Time): Unaught exception: Error: failed to connect to [undefined:27017]
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:553:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:140:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:512:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:830:16
    at process._tickCallback (node.js:415:13)
Sun Apr 13 2014 00:22:19 GMT+0000 (Coordinated Universal Time): Unaught exception: Error: failed to connect to [undefined:27017]
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:553:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:140:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:512:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:830:16
    at process._tickCallback (node.js:415:13)
Sun Apr 13 2014 00:22:24 GMT+0000 (Coordinated Universal Time): Unaught exception: Error: failed to connect to [undefined:27017]
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:553:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:140:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:512:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:830:16
    at process._tickCallback (node.js:415:13)
Sun Apr 13 2014 00:24:27 GMT+0000 (Coordinated Universal Time): Unaught exception: Error: failed to connect to [undefined:27017]
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:553:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:140:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:512:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:830:16
    at process._tickCallback (node.js:415:13)
Sun Apr 13 2014 00:29:03 GMT+0000 (Coordinated Universal Time): Unaught exception: Error: failed to connect to [undefined:27017]
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:553:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:140:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:512:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:830:16
    at process._tickCallback (node.js:415:13)
Sun Apr 13 2014 00:29:37 GMT+0000 (Coordinated Universal Time): Unaught exception: Error: failed to connect to [undefined:27017]
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:553:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:140:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:512:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:830:16
    at process._tickCallback (node.js:415:13)
Sun Apr 13 2014 00:34:30 GMT+0000 (Coordinated Universal Time): Unaught exception: Error: failed to connect to [undefined:27017]
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:553:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:140:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:512:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:830:16
    at process._tickCallback (node.js:415:13)
Sun Apr 13 2014 00:34:47 GMT+0000 (Coordinated Universal Time): Unaught exception: Error: failed to connect to [undefined:27017]
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:553:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:140:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:512:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:830:16
    at process._tickCallback (node.js:415:13)
Sun Apr 13 2014 00:35:32 GMT+0000 (Coordinated Universal Time): Unaught exception: Error: failed to connect to [undefined:27017]
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:553:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:140:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:512:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:830:16
    at process._tickCallback (node.js:415:13)
Sun Apr 13 2014 00:35:38 GMT+0000 (Coordinated Universal Time): Unaught exception: Error: failed to connect to [undefined:27017]
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:553:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:140:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:512:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:830:16
    at process._tickCallback (node.js:415:13)
Sun Apr 13 2014 00:39:22 GMT+0000 (Coordinated Universal Time): Unaught exception: Error: failed to connect to [undefined:27017]
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:553:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:140:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (D:\home\site\wwwroot\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:512:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:830:16
    at process._tickCallback (node.js:415:13)
